name: Deploy Dist

on:
  - push
  - workflow_dispatch

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        run: |
          echo "Cloning repo"
          echo "${{ github.repository }}"
          git clone https://github.com/${{ github.repository }}.git
